# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ChiuMethod <- function(data_r, exponential_r, potential_r, r_a = 0.5, eps_high = 0.5, eps_low = 0.15) {
    .Call('Clustering_ChiuMethod', PACKAGE = 'Clustering', data_r, exponential_r, potential_r, r_a, eps_high, eps_low)
}

timeseries_in_centers <- function(groups_v, ncenters) {
    .Call('Clustering_timeseries_in_centers', PACKAGE = 'Clustering', groups_v, ncenters)
}

compareClustering <- function(groups_1_v, ncenters_1, groups_2_v, ncenters_2) {
    .Call('Clustering_compareClustering', PACKAGE = 'Clustering', groups_1_v, ncenters_1, groups_2_v, ncenters_2)
}

compareParallelClustering <- function(groups_1_v, ncenters_1, groups_2_v, ncenters_2) {
    .Call('Clustering_compareParallelClustering', PACKAGE = 'Clustering', groups_1_v, ncenters_1, groups_2_v, ncenters_2)
}

compareParallelClusteringV2 <- function(groups_1_v, ncenters_1, groups_2_v, ncenters_2) {
    .Call('Clustering_compareParallelClusteringV2', PACKAGE = 'Clustering', groups_1_v, ncenters_1, groups_2_v, ncenters_2)
}

dist_ <- function(pInBigMat, pOutBigMat) {
    invisible(.Call('Clustering_dist_', PACKAGE = 'Clustering', pInBigMat, pOutBigMat))
}

BigArmaEuc <- function(pInBigMat, pOutBigMat) {
    invisible(.Call('Clustering_BigArmaEuc', PACKAGE = 'Clustering', pInBigMat, pOutBigMat))
}

BigExpPot <- function(pInBigMat, pOutBigExp, pOutBigPot, alpha) {
    invisible(.Call('Clustering_BigExpPot', PACKAGE = 'Clustering', pInBigMat, pOutBigExp, pOutBigPot, alpha))
}

