// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ErrorForecast
RObject ErrorForecast(SEXP data_forecast, SEXP centers_);
RcppExport SEXP TimeSeriesForecast_ErrorForecast(SEXP data_forecastSEXP, SEXP centers_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type data_forecast(data_forecastSEXP);
    Rcpp::traits::input_parameter< SEXP >::type centers_(centers_SEXP);
    rcpp_result_gen = Rcpp::wrap(ErrorForecast(data_forecast, centers_));
    return rcpp_result_gen;
END_RCPP
}
