# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ErrorForecast <- function(data_forecast, centers_) {
    .Call('TimeSeriesForecast_ErrorForecast', PACKAGE = 'TimeSeriesForecast', data_forecast, centers_)
}

